-- +migrate Up
CREATE TABLE Ticket(
	ID INT NOT NULL AUTO_INCREMENT,
	QueueID INT NOT NULL,
	Subject TEXT NOT NULL,
	Status INT NOT NULL,
	Priority INT NOT NULL,
	CreatedAt TIMESTAMP NOT NULL,

	PRIMARY KEY (ID),
	FOREIGN KEY (QueueID) REFERENCES Queue(ID)
);

-- +migrate Down
DROP TABLE Ticket;
